//created on: 4 nov. 2019
package rules

import domain.*;

rule "QRS Complex Creation"
	when
		$q: Q($c : cycle)
		$r: R(cycle == $c)
		$s: S(cycle == $c) 
	then
		QRSComplex qrs = new QRSComplex($q.getStart(), $s.getEnd(), $c);
		insert(qrs);
		System.out.println("Se ha creado el complejo QRS del ciclo numero " + $c);
end

rule "QT Intervale Creation"
	when
		$q: Q($c : cycle)
		$t: T(cycle == $c)
	then
		QTIntervale qt = new QTIntervale($q.getStart(), $t.getEnd(), $c);
		insert(qt);
		System.out.println("Se ha creado el intervalo QT del ciclo numero " + $c);
end

rule "ST Segment Creation"
	when
		$s: S($c : cycle)
		$t: T(cycle == $c) 
	then
		STSegment st = new STSegment($s.getStart(), $t.getEnd(), $c);
		insert(st);
		System.out.println("Se ha creado el segmento ST del ciclo numero " + $c);
end