//created on: 4 nov. 2019
package domain

import domain.*;


rule "Cycle Creation"
	when
		$p: P($c : cycle)
		$q: Q(cycle == $c)
		$r: R(cycle == $c)
		$s: S(cycle == $c) 
		$t: T(cycle == $c)
	then
		Cycle cy = new Cycle ($c, $p, $q, $r, $s, $t);
		insert(cy);
		System.out.println("Se ha creado el ciclo numero " + $c);
end

rule "Hypokalemia"
	when
		//$cy: Cycle(tWave.peak < 0.1, $c : cycle)
		//$cy2 : Cycle(cycle == $c+1, tWave.peak < 0.1)
		$nv : NormalValues()
		$cy: Cycle(tWave.peak < $nv.minPeakWaveT)
	then
		System.out.println("TIENES HIPOPOTASEMIA, CORRE!");
end

rule "Hypokalcemia"
	when
		$nv : NormalValues()
		$cy : Cycle(qt.duration > $nv.maxQTDuration)
	then
		System.out.println("TIENES HIPOCALCEMIA DIOOSSSS, CORRE!");
end

rule "AMI"
	when
		$nv : NormalValues()
		$cy : Cycle(tWave.peak > $nv.maxPeakWaveT)
	then
		System.out.println("QUE TE ME MUEREEEES, INFARTO DE MIOCARDIO AGUDO");
end